language: python
python:
    - 3.6
    - 3.7
    - 3.8
    - 3.9
notifications:
    email: false

before_install:
    - sudo apt-get update
    - sudo apt-get -y install python-pip
    - sudo pip install --upgrade pip
    - pip install --upgrade pip
    - pip install pep8

script:
    - find . -name \*.py -exec pep8 --ignore=E402,E501 {} +
