language: python
python:
    - 3.8
notifications:
    email: false

before_install:
    - sudo apt-get update
    - sudo apt-get -y install python-pip
    - sudo pip install --upgrade pip
    - pip install --upgrade pip
    - pip install pycodestyle yamllint

script:
    - pycodestyle --ignore=E402,E501 .
    - yamllint test-code/
