---

- hosts: localhost
  gather_facts: false
  tasks:
    - name: "get list of eks clusters"
      aws_eks_cluster_info:
      register: __all
    - name: "get fargate profiles for given cluster"
      aws_eks_cluster_info:
        name: "{{ __all.clusters[1] }}"
        list_fargate_profiles: true
    - name: "get nodegroups for given cluster"
      aws_eks_cluster_info:
        name: "{{ __all.clusters[1] }}"
        list_nodegroups: true
    - name: "get list of addons for given cluster"
      aws_eks_cluster_info:
        name: "{{ __all.clusters[1] }}"
        list_addons: true
    - name: "get details about given cluster"
      aws_eks_cluster_info:
        name: "{{ __all.clusters[1] }}"
        describe_cluster: true
