name: Greetings

on:
  issues:
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.ACTION_SECRET }}
        pr-message: 'Thank You!'
